// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmd_display_selected_object_dialog", "object_attr", "main_frame");
            //akit.ValueChange("beam_1", "PRELIM_MARK", "");

            akit.TabChange("beam_1", "tw", "tab6");
            akit.PushButton("on_off_button", "beam_1");
            akit.TabChange("column_1", "tw", "tab6");
            akit.PushButton("on_off_button", "column_1");
        }
    }
}
