// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
			akit.PushButton("dia_draw_display_all", "Drawing_selection");
            akit.Callback("gdr_menu_select_active_draw", "", "main_frame");
            akit.PushButton("dia_draw_filter_by_parts", "Drawing_selection");
        }
    }
}
